
package fr.paris10.miage.procs.exercice4.radars.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SystemeAmendes", targetNamespace = "http://service.radars.exercice3.procs.miage.paris10.fr/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SystemeAmendes {


    /**
     * 
     * @param arg0
     */
    @WebMethod
    @Action(input = "http://service.radars.exercice3.procs.miage.paris10.fr/SystemeAmendes/enregistrerRequest", output = "http://service.radars.exercice3.procs.miage.paris10.fr/SystemeAmendes/enregistrerResponse")
    public void enregistrer(
        @WebParam(name = "arg0", partName = "arg0")
        Voiture arg0);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://service.radars.exercice3.procs.miage.paris10.fr/SystemeAmendes/signalerRequest", output = "http://service.radars.exercice3.procs.miage.paris10.fr/SystemeAmendes/signalerResponse")
    public int signaler(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        int arg2);

    /**
     * 
     * @param arg0
     * @return
     *     returns fr.paris10.miage.procs.exercice3.radars.service.AmendeArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://service.radars.exercice3.procs.miage.paris10.fr/SystemeAmendes/listerRequest", output = "http://service.radars.exercice3.procs.miage.paris10.fr/SystemeAmendes/listerResponse")
    public AmendeArray lister(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @Action(input = "http://service.radars.exercice3.procs.miage.paris10.fr/SystemeAmendes/payerRequest", output = "http://service.radars.exercice3.procs.miage.paris10.fr/SystemeAmendes/payerResponse")
    public void payer(
        @WebParam(name = "arg0", partName = "arg0")
        int arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        String arg2);

}
